name: Automatic tests for plugin using QGIS

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  testing_min_qgis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Pull qgis image (3.34)
      run: docker pull qgis/qgis:3.34

    - name: Run requirements and tests
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/usr/src/plugin \
          -w /usr/src/plugin \
          -e PYTHONPATH=/usr/src \
          qgis/qgis:3.34 \
          sh -c "
            apt-get update && apt-get install -y xvfb &&
            python3 -m pip install -r requirements.txt --break-system-packages &&
            export PYTHONPATH=\$PYTHONPATH:/usr/src/plugin
            xvfb-run python3 -m unittest discover -v -s test -t .
          "
